version: 2
jobs:
  build:
    docker:
      - image: zondax/circleci@sha256:37f78ab294b35a055768c2305b3f13813e55fb9db4e65f72745ede61dd842c08
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: apt-get update && apt-get -y install python3.6 && apt -y install python3-pip && pip3 install conan
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      # Unfortunately need to disable leak sanitizer https://github.com/google/sanitizers/issues/916
      # Still run all other ASAN components
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_ledger:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - BOLOS_SDK_IGNORE=/home/zondax/project/deps/nanos-secure-sdk
      - BOLOS_ENV_IGNORE=/opt/bolos
    steps:
      - checkout
      # Docker entrypoint is not considered
      - run: git submodule update --init --recursive
      - run:
          # todo: consider splitting the container cross-compiler upgrade step into its own step: make compiler_container
          # todo: consider upgrading CircleCI to allow caching docker images across builds to speed up the step the container cross-compiler upgrade step
          name: Build
          command: |
            make
      - run:
          name: Install node + yarn
          command: |
            source /opt/circleci/.nvm/nvm.sh
            nvm install 12.16.2
            nvm use 12.16.2
            rm -rf ~/.yarn
            npm install -g yarn
            which yarn
            yarn -v
      - run:
          name: Docker pull speculos + yarn install
          command: |
            make speculos_install
      - run:
          # todo: consider upgrading CircleCI to allow parallel jobs, and splitting this into a separate CircleCI jobs which run in parallel on separate speculos container instances
          name: Run speculos tests
          command: |
            make speculos_port_5001_test

  test_fuzz_crash_fixes:
    docker:
      - image: zondax/circleci@sha256:37f78ab294b35a055768c2305b3f13813e55fb9db4e65f72745ede61dd842c08
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt update && sudo apt -y install clang-10
      - run:
          name: Build
          command: |
            cmake -B build \
                    -DCMAKE_C_COMPILER=clang-10 \
                    -DCMAKE_CXX_COMPILER=clang++-10 \
                    -DCMAKE_BUILD_TYPE=Debug \
                    -DENABLE_FUZZING=1 \
                    -DENABLE_SANITIZERS=1 \
                    .
            make -C build
      - run: ./run-fuzz-crashes.py

#  test_zemu:
#    machine:
#      image: ubuntu-1604:201903-01
#    working_directory: ~/repo
#    environment:
#      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
#    steps:
#      - checkout
#      - run: git submodule update --init --recursive
#      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
#      - run:
#          name: Build Ledger app
#          command: |
#            make
#      - run:
#          name: Install node + yarn
#          command: |
#            nvm install 12.16.2
#            nvm use 12.16.2
#            npm install -g yarn
#      - run:
#          name: Build/Install build js deps
#          command: |
#            nvm use 12.16.2
#            make zemu_install
#      - run:
#          name: Run zemu tests
#          command: |
#            nvm use 12.16.2
#            make zemu_test
#          no_output_timeout: 30m

  build_package:
    docker:
      - image: zondax/builder-bolos:latest
    environment:
      - BOLOS_SDK=/home/zondax/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Build
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make
      - run: /home/zondax/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(/home/zondax/project/app/pkg/zxtool.sh version) /home/zondax/project/app/pkg/zxtool.sh

workflows:
  version: 2

  default:
    jobs:
      - build
      - build_ledger
      - build_package:
          requires:
            - build
            - build_ledger
#           - test_zemu
          filters:
            branches:
              only:
                - master
