name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_build_debug:
    name: Build debug
    strategy:
      fail-fast: false
      matrix:
        cfg:
          [
            { device: "NANO_S", sdk: "$NANOS_SDK" },
            { device: "NANO_X", sdk: "$NANOX_SDK" },
            { device: "NANO_SP", sdk: "$NANOSP_SDK" },
          ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build ${{ matrix.cfg.device }}
        run: |
          make clean
          make BOLOS_SDK=${{ matrix.cfg.sdk }} DEBUG=1
      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: flow-app-debug-${{ matrix.cfg.device }}
          path: bin

  job_scan_build:
    name: Clang Static Analyzer
    needs: job_build_debug
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: scan-build
          path: scan-build
