name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

env:
  MAKE_OPT: --no-print-directory -C deps/ledger-zxlib/

jobs:
  job_build_debug:
    name: Build debug
    strategy:
      fail-fast: false
      matrix:
        cfg:
          [
            { device: "NANO_S", sdk: "$NANOS_SDK" },
            { device: "NANO_X", sdk: "$NANOX_SDK" },
            { device: "NANO_SP", sdk: "$NANOSP_SDK" },
          ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build ${{ matrix.cfg.device }}
        run: |
          make clean
          make BOLOS_SDK=${{ matrix.cfg.sdk }} DEBUG=1
      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: flow-app-debug-${{ matrix.cfg.device }}
          path: bin

  job_scan_build:
    name: Clang Static Analyzer
    needs: job_build_debug
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: scan-build
          path: scan-build

  job_unit_test:
    name: C++ unit tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build and run unit tests
        run: |
          pip3 install conan
          conan profile detect
          export BOLOS_SDK=
          make ${{ env.MAKE_OPT}} cpp_test

  job_speculos_tests:
    name: Speculos tests
    needs: job_build_debug
    strategy:
      fail-fast: false
      matrix:
        device: ["NANO_S", "NANO_X", "NANO_SP"]
        port: ["5001", "5002"]
        include:
          - device: NANO_S
            port: "5003"
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v3
        with:
          name: flow-app-debug-${{ matrix.device }}
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          make ${{ env.MAKE_OPT}} speculos_install

      - name: Run tests
        run: |
          make ${{ env.MAKE_OPT}} TARGET_NAME=${{ matrix.device }} speculos_port_${{ matrix.port }}_test

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: speculos-${{ matrix.device }}-${{ matrix.port }}-log
          path: tests_speculos/speculos-port-${{ matrix.port }}.log
