name: Compilation & tests

on: [push, pull_request]

jobs:
  job_build_debug:
    name: Build debug
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build Nano S
        run: |
          make clean
          make DEBUG=1
      - name: Upload app NanoS binary
        uses: actions/upload-artifact@v2
        with:
          name: flow-app-debug-nanos
          path: bin

      - name: Build Nano X
        run: |
          make clean
          TARGET_NAME=TARGET_NANOS BOLOS_SDK=$NANOX_SDK make DEBUG=1
      - name: Upload app Nano X binary
        uses: actions/upload-artifact@v2
        with:
          name: flow-app-debug-nanox
          path: bin

      - name: Build Nano S+
        run: |
          make clean
          TARGET_NAME=TARGET_NANOS2 BOLOS_SDK=$NANOSP_SDK make DEBUG=1
      - name: Upload app Nano S+ binary
        uses: actions/upload-artifact@v2
        with:
          name: flow-app-debug-nanosp
          path: bin

  job_scan_build:
    name: Clang Static Analyzer
    needs: job_build_debug
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build

  job_unit_test:
    name: C++ unit tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and run unit tests
        run: |
          pip3 install conan
          conan profile detect
          export BOLOS_SDK=
          make --no-print-directory -C deps/ledger-zxlib/ cpp_test

  job_speculos_nanos_tests_5001:
    name: NanoS Speculos 5001/3 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanos
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_S REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5001_test
          TARGET_NAME=NANO_S REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5003_test

      - name: Upload Speculos 5001s log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5001s-log
          path: tests_speculos/speculos-port-5001.log
      - name: Upload Speculos 5003s log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5001s-log
          path: tests_speculos/speculos-port-5003.log

  job_speculos_nanos_tests_5002:
    name: NanoS Speculos 5002 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanos
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_S REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5002_test

      - name: Upload Speculos log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5002s-log
          path: tests_speculos/speculos-port-5002.log

  job_speculos_nanox_tests_5001:
    name: NanoX Speculos 5001 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanox
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_X REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5001_test

      - name: Upload Speculos 5001s log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5001x-log
          path: tests_speculos/speculos-port-5001.log

  job_speculos_nanox_tests_5002:
    name: NanoX Speculos 5002 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanox
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_X REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5002_test

      - name: Upload Speculos log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5002x-log
          path: tests_speculos/speculos-port-5002.log

  job_speculos_nanosp_tests_5001:
    name: NanoS+ Speculos 5001 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanosp
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_SP REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5001_test

      - name: Upload Speculos 5001s log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5001sp-log
          path: tests_speculos/speculos-port-5001.log

  job_speculos_nanosp_tests_5002:
    name: NanoS+ Speculos 5002 tests
    needs: job_build_debug
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: flow-app-debug-nanosp
          path: bin

      - name: install speculos
        run: |
          export BOLOS_SDK=
          REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_install

      - name: Run tests
        run: |
          TARGET_NAME=NANO_SP REPO_DIR=$(pwd) make --no-print-directory -C deps/ledger-zxlib/ speculos_port_5002_test

      - name: Upload Speculos log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-5002sp-log
          path: tests_speculos/speculos-port-5002.log
